### ISSUE TITLE
Import study - Attributes construct error

### ISSUE THREAD

**Issue by PEvelynNguyen** [qualintitative/egoweb#14]
I try to import a study that I previously exported but encountered this error every time:

Error 500

simplexml_load_file(): /tmp/phpgUTgLI:64: parser error : attributes construct error

Do you have a solution to this problem? I followed the instructions, which seem simple and straightforward.

**Comment by qualintitative** [comment]
Whenever I see Error 500 I enter 

~/admin/migrate

Into a browser address window, replacing "~" with the url you are accessing egoweb.  That usually does the trick, especially after updating to a new version of EgoWeb.  This updates the tables that may have changed with the latest version of EgoWeb.  

I have had some trouble running migrate on my local machine lately but it has worked on servers.  Let me know if this does not work.

**Comment by PEvelynNguyen** [comment]
I've done it and tried many times. Just tried again but it didn't work unfortunately. It's the same error.

**Comment by qualintitative** [comment]
OK got some feedback from David.  He thinks some type of character in the file is throwing off the import process.  We have fixed a lot of these issues but there might still be some special characters that need to be addressed.  When there is text in the file, some characters have special meaning for the programming language (PHP I guess) and we have to put something in to filter these out.  

Can you share your .study file with me?  I'm not sure how else to diagnose.

**Comment by PEvelynNguyen** [comment]
Hi David, 

I'm having this problem again. We're migrating from AWS to Linode and I need to import the study to the new egoweb site on Linode. First, it said the file exceeded the max upload size, so I modified the max upload size and max post size in php.ini. Problem solved. 

Then it's Error 500 again, but the description is a bit different as below:

Error 500
simplexml_load_file(): /tmp/phpevRT3T:68: parser error : attributes construct error

I'm sorry I couldn't send you the .study file coz it has data :(. Is there any other way we could work this out?

**Comment by qualintitative** [comment]
Hi Evelyn, 

We have done a lot of changes recently with import / export and you might need to do some updating of servers to make your data go from one server to another smoothly.  We added a server to server sync feature which makes things much nicer.  To take advantage of this, both servers need to be running the same version of EgoWeb. 

To do this, first, I recommend updating both servers to the latest "dev" branch.  We were doing a lot of tweaking of the import/export process and I think we fixed most/all of the bugs to import/export processes.  However, both servers need to be running the same versions or else there are likely to be problems.  

Once you update the servers, make sure you go to "authoring" of each of the studies on the servers where they are stored and then click on "questions".  If they were created in the old format, there will be an "Convert" button.  We revamped the authoring so that there can be flexible questionnaire design and multiple name generators.  I haven't had time to fully revise the wiki instructions but there is info about the multiple name generators here:  http://www.qualintitative.com/wiki/doku.php/multinamegenerator.  I saw problems with the import/export process for studies in newer servers that have not been converted yet, so please do that. 

Once both servers have the latest "dev" (this will soon be the "master" branch once we fix a few more bugs) go to import/export.  At the bottom you will see new features.  "Save External Server Credentials" allows you to store server urls, user ids, and passwords so that a study and responses can be sent from that server to another one.  Once you save server credentials, you can use the "Send Study to Server" to pick a study and/or data to send to the server.  We have not put in a "delete" server option yet. This makes it so that you do not have to export a .study file and import it in the new server.  You can still do that but big mismatches between server versions might cause problems that we have not debugged yet.  

Try that and let me know if it does not fix the problems.

**Comment by PEvelynNguyen** [comment]
Yayy! Did as you instructed and got the site up and running. Thanks a lot for the great work of maintaining and improving the software.
