### ISSUE TITLE
Data processing - network statistics for alter expressions not shown

### ISSUE THREAD

**Issue by PEvelynNguyen** [qualintitative/egoweb#15]
In data processing, the net work statistics options for alter expressions are not shown. Only the options for alter pair expressions are shown. Furthermore, when I had selected an available option, nothing happened when I clicked on the Export Ego-Alter data and Eport Alter Pair data buttons. 
![data processing](https://cloud.githubusercontent.com/assets/18224789/23921679/860e0c46-08cd-11e7-95e5-a41dee9e5001.jpg)

**Comment by qualintitative** [comment]
The expressions are only showing up for alter pair because they are for calculating statistics based on alter-alter ties.  For example, density.  The alter-pair expressions define when there are edges between the nodes (the alters).  The other expressions are not relevant for any of the calculations because they have nothing to do with ties between alters.  The statistics are added to the export along with the raw data -- if you have data and have selected responses.  I can't tell if you have that based on the screen shot.  Did you do test interviews and enter data for at least one respondent?

**Comment by PEvelynNguyen** [comment]
Thanks for the explanation. 

I had data and had selected responses, but it didn't work. However, I tried it again today and it worked. I don't know what the problem was but it works now. Maybe some server connection issue.
