### ISSUE TITLE
Install Egoweb on Linode.com with stackscript

### ISSUE THREAD

**Issue by PEvelynNguyen** [qualintitative/egoweb#19]
Hello David,

Hope you're doing well. 

I'm trying to install Egoweb on Linode. I ran the egoweb stackscript and I think I successfully deployed Egoweb. Is there anything else I need to do after running the stackscript & booting the linode? I can ping the server, can access it via Putty & Lish. However, I can't access egoweb via its public IP (by entering the IP on a web browser's address bar). 

Thanks for your help.
Evelyn

**Comment by PEvelynNguyen** [comment]
I tried a few dozen times with stackscript installation and was not able to access egoweb via its public ips (the installation process went smoothly, I didn't see any warning or failures). So I tried to set it up manually and it has finally worked. However, it'd be great if you could look into this issue and get it fixed for future users. Stackscript installation is so much more convenient and easy.

**Comment by qualintitative** [comment]
Hi Evelyn, 

I'm glad you got it going.  There were a bunch of changes in how the servers are set up that broke the stack script.  I had a programmer working on it recently to debug.  He got it to run and set up a server but I haven't been able to run it myself because my Linodes had things running in them.  Did you run the "EgoWeb Updated" stack script?  That is the newest one.  As soon as I move data from one of my Linodes I'll start experimenting with the stack script and develop better instructions.  I remember from before that there are odd times that it runs fine and other times it gets stuck and I never knew exactly why.  I really depend on the stack scripts so I would like to make sure it works also.

**Comment by PEvelynNguyen** [comment]
Yes, I tried both the "working" & "updated" stack scripts many times, none of which worked. Since I have been able to install manually, I haven't tried again since then.
